# Generated by Django 3.2.3 on 2021-06-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tascDesc',
            new_name='taskDesc',
        ),
    ]
