# Generated by Django 3.2.3 on 2021-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='counts',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
